### ISSUE TITLE
Fuzzy matching?

### ISSUE THREAD

**Issue by qazip** [PonasKovas/rlaunch#11]
It would be nice if rlaunch supported fuzzy maching.

For example, I have a .desktop entry called "no-ads". Typing "no ads" should return "no-ads"...

**Comment by PonasKovas** [comment]
Good idea.

I'll try to look into this soon

**Comment by PonasKovas** [comment]
f5ea52e implemented.

**Comment by qazip** [comment]
Awesome! Just one thing:

Typing "qb" returns 2 matches, in this order:

- Qt qDbusViewer;
- qBittorrent;

Any idea why "qBittorrent" is not the first match?

**Comment by PonasKovas** [comment]
It appears that the algorithm is not actually case insensitive, I'll make a quick fix for it

**Comment by qazip** [comment]
I don't think that's it actually. "qb", "QB", "qB" and "Qb" all return the same thing, in the same order and that is the order from my previous message..

**Comment by PonasKovas** [comment]
However if the target strings become all lowercase, entering "qb" returns "qbittorrent" first

Edit: check 06b180a out

**Comment by qazip** [comment]
@PonasKovas, it works as intended now, thank you!

You should bump the version though. `rlaunch --version` still gives 1.3.9.

**Comment by PonasKovas** [comment]
Oh yeah, thanks, I keep forgetting to do that

**Comment by PonasKovas** [comment]
I'm personally not really happy with how it works now. It seems that the algorithm is not giving enough significance to whether the target string starts with the pattern. If I type `disco`, obviously `discord` should be the first suggestions, but for some reason things like `pppoe-discovery` and `plasma-discover-update` get higher (or equal) scores.

**Comment by PonasKovas** [comment]
@qazip opinion on fe1c4a7 ?

**Comment by qazip** [comment]
Works perfectly for me. 

ffx gives firefox
qb gives qbittorrent first
noads gives no-ads

**Comment by PonasKovas** [comment]
That's great, it seems to be working for my cases too.

Feel free to re-open if you encounter any more bugs or have any more questions.
