### ISSUE TITLE
Create a NixOS package

### ISSUE THREAD

**Issue by nonetrix** [PonasKovas/rlaunch#14]
It would be great if this had a NixOS package I don't know how hard this is but would make my setup a lot more convenient

**Comment by PonasKovas** [comment]
I am not familiar with NixOS and it's packages and I do not have the capacity to take on this. If anyone else wants to do it, I'm open to accepting PRs.

**Comment by danc86** [comment]
FYI I have a PR against nixpkgs for this: https://github.com/NixOS/nixpkgs/pull/139411
