### ISSUE TITLE
Error running on Manjaro Linux

### ISSUE THREAD

**Issue by wito-dev** [PonasKovas/rlaunch#2]
```-> % rlaunch
X Error of failed request:  BadName (named color or font does not exist)
Major opcode of failed request:  45 (X_OpenFont)
Serial number of failed request:  9
Current serial number in output stream:  11
```

I compiled from AUR:
https://aur.archlinux.org/packages/rlaunch/

**Comment by PonasKovas** [comment]
This means that the default font is not available on your system.

~~Try using `xfontsel` to find a font that is available and then specify it when running `rlaunch` with the `-f` argument.~~

~~for example:~~
```sh
rlaunch -f="-*-fixed-medium-*-*-*-18-*-*-*-*-*-*-*"
```

**Comment by PonasKovas** [comment]
@Albitos I just released a new version of rlaunch that uses FreeType font rasterizer, so this shouldn't be an issue anymore. Compile (or [download](https://github.com/PonasKovas/rlaunch/releases/download/1.3.0/rlaunch)) the new (1.3.0+) version.

I will close this issue now, but if it still doesn't work for you, feel free to re-open it.
