### ISSUE TITLE
Hidden applications are shown

### ISSUE THREAD

**Issue by felipec** [PonasKovas/rlaunch#8]
I have a bunch of application modifications in `~/.local/share/applications` where I add 'Hidden=true' so they are not shown.

AFAIK this is an appropriate way to hide applications, and at least in Xfce4 they are not shown.

But they appear in rlaunch.

**Comment by PonasKovas** [comment]
That's easy to fix, thanks for reporting. I will probably fix it in a few hours.

**Comment by PonasKovas** [comment]
@felipec Fixed.

**Comment by felipec** [comment]
I tried the fix, it doesn't work.

Judging from the code if I add a Hidden=true line to `~/.local/share/applications/qv4l2.desktop` it will simply ignore that desktop file. The point of such file is to override the `/usr/share/applications/qv4l2.desktop` file.

The specification says so:

https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html

**Comment by felipec** [comment]
You should also consider handling NoDisplay.

**Comment by PonasKovas** [comment]
Should `NoDisplay` just ignore the desktop file or override like you said about `Hidden`?

**Comment by felipec** [comment]
Both should do the same in rlaunch.

If you read the specification `Hidden` should make it as if the application was never installed. `NoDisplay` just would make the application not displayed in menus. The difference is for other purposes like mime-type handling.

The important part is that only the first desktop file is considered, the rest ignored. This would make my personal files override the system ones.

**Comment by PonasKovas** [comment]
ok, thanks, I will try to implement this by monday.

**Comment by PonasKovas** [comment]
@felipec I think I fixed it, can you try the new version out? If it works, feel free to close this issue.

**Comment by felipec** [comment]
Seems to work fine now. Thanks.
